% -------------------------------------------------------------------
%  Generated by MATLAB on 17-Jan-2026 14:53:08
%  MATLAB version: 25.2.0.3055257 (R2025b) Update 2
% -------------------------------------------------------------------
saveVarsMat = load('bisection.mat');

a = 1.1347241383045912;

b = 1.1347241401672363;

f = saveVarsMat.f; % <1x1 function_handle> unsupported class

i = 30;

maxIter = 100;

p = 1.1347241392359138;

sfa = -1;

sfp = -1;

toler = 1E-9;

clear saveVarsMat;
